pipeline {
    agent none
    stages {
        stage('Build Maven') {
	 agent {
            docker {
            image 'maven:3-alpine'
            args '-v $HOME/.m2:/root/.m2'
           }
        }
            steps {
                sh 'mvn -f SimpleDemo/pom.xml clean install'
            }
        }
	stage('Docker preparation') {
	    agent any
            steps {
                sh 'docker build -f SimpleDemo/Dockerfile -t simpledemo .'
            }
        }
	stage('Launch') {
	    agent any
            steps {
                sh 'docker run -d -p 8085:8085 simpledemo'
		sh 'echo Launched successfully!'
            }
        }

    }
}
