pipeline {
    agent none
    stages {
        stage('Build') {
	 agent {
            docker {
            image 'maven:3-alpine'
            args '-v $HOME/.m2:/root/.m2'
           }
        }
            steps {
                sh 'mvn -f SimpleDemo/pom.xml clean install'
            }
        }
	stage('Launch') {
	    agent any
            steps {
                sh 'docker build -f SimpleDemo/Dockerfile -t SimpleDemo'
            }
        }

    }
}
